apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "videoprocessing.fullname" . }}
  labels:
    {{- include "videoprocessing.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | indent 4 }}
